<section class="side-bar">
    <div class="left">
        <h4>ADMINISTRATION</h4>
        <h3>Espace de gestion</h3>
    </div>
    <div class="buttons">
        <!-- //si la route est egale a question-edit, la classe devient active et du coup l'onglet en haut est coloré -->
        <a href="?route=questions-edit" class="<?= (($_GET['route'] ?? '') === 'questions-edit') ? 'active' : '' ?>">Questions</a> 
        <a href="?route=themes-edit" class="<?= (($_GET['route'] ?? '') === 'themes-edit') ? 'active' : '' ?>">Thèmes</a>
        <a href="?route=users-edit" class="<?= (($_GET['route'] ?? '') === 'users-edit') ? 'active' : '' ?>">Utilisateurs</a>
        <a href="?route=stats-display" class="<?= (($_GET['route'] ?? '') === 'stats-display') ? 'active' : '' ?>">Statistiques</a>
    </div> 
    <a href="?route=home"> Retour à l'accueil</a>
</section>