<section class="side-bar">
    <div class="left">
        <h4>ADMINISTRATION</h4>
        <h3>Espace de gestion</h3>
    </div>
    <div class="buttons">
    <a href="?route=questions-edit" class="active">Questions</a>
    <a href="?route=themes-edit">Thèmes</a>
    <a href="?route=users-edit">Utilisateurs</a>
    <a href="?route=stats-edit">Statistiques</a>
</div>
    <a href="?route=home"> Retour à l'accueil</a>
</section>