<section class="quiz-ms-game">
    <div class="info-container">
        <div class="question-number">
            <h4>Question <?=htmlspecialchars($currentIndex +1) ?> /<?= htmlspecialchars($totalQuestion)?></h4>
        </div>
        <span class="theme"><?= htmlspecialchars($currentQuestion->getTheme()->getName())?></span>
        <span class="timer" id="timer"> </span>
        <a href="?route=home" class="arrow-back" title="Quitter le quiz">
            <i class="fa-solid fa-xmark"></i> 
        </a>
    </div>
    <div class="game-container">
        <div class="question">
            <h3><?=htmlspecialchars($currentQuestion->getStatement())?></h3>
        </div>
        <form action="?route=submit-answer-ms" method="POST" class="quiz-form" id="quiz-form">
            <div class="answers">
                <?php foreach($answers as $answer): ?>
                    <button type="submit" name="answer_id" value="<?= $answer->getId() ?>" class="box-answer" data-correct="<?= $answer->getIsCorrect();?>">
                        <span><?= htmlspecialchars($answer->getAnswer()) ?></span>
                    </button>
                <?php endforeach; ?>
            </div>
        </form>
    </div>
    <div class="score">
        <p>Score actuel: <?= htmlspecialchars($score)?></p>
    </div>
    <script src="assets/js/quizThemeGame.js"></script>
    <script src="assets/js/timer.js"></script>
</section>