<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QCM GAME</title>
    <link rel="stylesheet" href="assets/css/global.css">

    <?php switch ($template) {
        case "auth/login.phtml": ?>
    <link rel="stylesheet" href="assets/css/login.css">
    <?php
            break;
        case "auth/register.phtml" :?>
    <link rel="stylesheet" href="assets/css/register.css">
    <?php
            break;
        case "home/home.phtml" :?>
    <link rel="stylesheet" href="assets/css/home.css">
    <?php
            break;
    } ?>
</head>
<body>
  <main> <?php require "partials/$template"; ?></main>
</body>
</html>