<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QCM GAME</title>
    <link rel="stylesheet" href="assets/css/global.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <?php switch ($template) {
        case "auth/login.phtml": ?>
    <link rel="stylesheet" href="assets/css/login.css">
    <?php
            break;
        case "auth/register.phtml" :?>
    <link rel="stylesheet" href="assets/css/register.css">
    <?php
            break;
        case "auth/profile.phtml" :?>
    <link rel="stylesheet" href="assets/css/profile.css">
    <?php
            break;
        case "home/home.phtml" :?>
    <link rel="stylesheet" href="assets/css/home.css">
    <?php
            break;
        case "theme/themeHome.phtml" :?>
    <link rel="stylesheet" href="assets/css/themeHome.css">
    <?php
            break;
        case "theme/quizThemeGame.phtml" :?>
    <link rel="stylesheet" href="assets/css/quizThemeGame.css">
    <?php
            break;
        case "theme/resultsTheme.phtml" :?>
    <link rel="stylesheet" href="assets/css/resultsTheme.css">
    <?php
            break;
        case "cultureGenerale/quizCultureGenerale.phtml" :?>
    <link rel="stylesheet" href="assets/css/quizCGC.css">
    <?php
            break;
        case "cultureGenerale/resultsCGC.phtml" :?>
    <link rel="stylesheet" href="assets/css/resultsCGC.css">
    <?php
            break;
        case "mortSubite/quizMortSubite.phtml" :?>
    <link rel="stylesheet" href="assets/css/quizMS.css">
    <?php
            break;
        case "stats/statsHome.phtml" :?>
    <link rel="stylesheet" href="assets/css/statHome.css">
    <?php
            break;
        case "mortSubite/resultsMS.phtml" :?>
    <link rel="stylesheet" href="assets/css/resultsMS.css">
    <?php
            break;
        case "admin/_headerAdministration.phtml" :?>
    <link rel="stylesheet" href="assets/css/_headerAdministration.css">
    <?php
            break;
        case "admin/questionsEdit.phtml" :?>
    <link rel="stylesheet" href="assets/css/questionsEdit.css">
    <?php
            break;
        case "admin/questionsAdd.phtml" :?>
    <link rel="stylesheet" href="assets/css/questionsAdd.css">
    <?php
            break;
        case "admin/usersDisplay.phtml" :?>
    <link rel="stylesheet" href="assets/css/usersDisplay.css">
    <?php
            break;
        case "admin/statsDisplay.phtml" :?>
    <link rel="stylesheet" href="assets/css/statsDisplay.css">
    <?php
            break;
    } ?>
</head>
<body>
  <main> <?php require "partials/$template"; ?></main>
</body>
</html>